name: Branch Typescript Pull

on:
  pull_request:
    branches:
      - refactor/typescript

jobs: 
  install:
    name: Install Dependencies
    runs_on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    - name: Cache node_modules
    uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn Install
      run: yarn install
  